[package]
name = "price"
version = "0.1.0"
authors = ["valentine-mario <valentine13400@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = [ "derive"] }
safe-mix = { default-features = false, version = '1.0.0' }
# substrate deps
frame-support = { default-features = false, version = "2.0.0" }
frame-system = { default-features = false, version = "2.0.0" }
# pallets
fetch-price = { default-features = false, package = "pallet-price-fetch", version = "1.2.0", path = "../fetch-price" }

[dev-dependencies]
sp-core = { default-features = false, version = "2.0.0-alpha.5" }
sp-io = { default-features = false, version = "2.0.0-alpha.5" }
sp-runtime = { default-features = false, version = "2.0.0-alpha.5" }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'safe-mix/std',
    'frame-system/std',
    'fetch-price/std',
]